export const Users = [
    {
        id:1,
        profilePicture: "assests/profile/KG.jpg",
        username: "Kavya Gupta",
    },
    {
        id:2,
        profilePicture: "assests/profile/VN.jpg",
        username: "Vanshika Nigam",
    },
    {
        id:3,
        profilePicture: "assests/profile/AC.jpg",
        username: "Anju Chaudhari",
    },
    {
        id:4,
        profilePicture: "assests/profile/SP.jpg",
        username: "Seema Patel",
    },
    {
        id:2,
        profilePicture: "assests/profile/PP.jpg",
        username: "Priya Pal",
    },
    {
        id:5,
        profilePicture: "assests/profile/VN.jpg",
        username: "Vanshika",
    },
    {
        id:6,
        profilePicture: "assests/profile/RK.jpg",
        username: "Reetika",
    },
    {
        id:7,
        profilePicture: "assests/profile/AG.jpg",
        username: "Ameesha Gupta",
    },
    {
        id:8,
        profilePicture: "assests/profile/KG.jpg",
        username: "Kavya Gupta",
    },
    {
        id:9,
        profilePicture: "assests/profile/VN.jpg",
        username: "Vanshika Nigam",
    },
    {
        id:10,
        profilePicture: "assests/profile/VN.jpg",
        username: "Vanshika Nigam",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Love For All, Hatred For None.",
        photo: "assests/post/tem.jpg",
        date: "5 min ago",
        userId: 1,
        like: 32,
        comment: 0,
    },
    {
        id: 2,
        desc: "Love For All, Hatred For None.",
        photo: "assests/post/sky.jpg",
        date: "5 min ago",
        userId: 2,
        like: 32,
        comment: 0,
    },
    {
        id: 3,
        photo: "assests/post/guava.jpg",
        date: "5 min ago",
        userId: 3,
        like: 15,
        comment: 1,
    },
    {
        id: 4,
        photo: "assests/post/tree.jpg",
        date: "30 mins ago",
        userId: 4,
        like: 25,
        comment: 2,
    },
    
    {
        id: 5,
        desc: "Love For All, Hatred For None.",
        photo: "assests/post/rr.jpg",
        date: "1 days ago",
        userId: 5,
        like: 32,
        comment: 0,
    },
    {
        id: 6,
        desc: "Love For All, Hatred For None.",
        photo: "assests/post/tree1.jpg",
        date: "5 days ago",
        userId: 6,
        like: 32,
        comment: 0,
    },
    {
        id: 7,
        desc: "Love For All, Hatred For None.",
        photo: "assests/post/flor.jpg",
        date: "6 days ago",
        userId: 7,
        like: 32,
        comment: 2,
    },
    {
        id: 8,
        desc: "Love For All, Hatred For None.",
        photo: "assests/post/gr.jpg",
        date: "1 week ago",
        userId: 8,
        like: 29,
        comment: 8,
    },
    {
        id: 9,
        desc: "Love For All, Hatred For None.",
        photo: "assests/post/bo.jpg",
        date: "12 days ago",
        userId: 9,
        like: 32,
        comment: 20,
    },
    {
        id: 10,
        desc: "Love For All, Hatred For None.",
        photo: "assests/post/flower1.jpg",
        date: "1 week ago",
        userId: 10,
        like: 32,
        comment: 18,
    },
    
];
